import {
  Archive,
  ArrowLeft,
  ArrowRight,
  BellNotification,
  Building,
  Calendar,
  CheckCircle,
  ClipboardCheck,
  Coins,
  Dashboard,
  DesignNib,
  Download,
  EditPencil,
  Eye,
  EyeClosed,
  FilterAlt,
  Folder,
  Group,
  Hexagon,
  InfoCircle,
  LogOut,
  Menu,
  MoreHoriz,
  MultiplePages,
  NavArrowDown,
  NavArrowLeft,
  NavArrowRight,
  NavArrowUp,
  Plus,
  Refresh,
  Search,
  Settings,
  Sort,
  SortDown,
  TaskList,
  Trash,
  Upload,
  UserPlus,
  WarningTriangle,
  WarningCircle,
  Xmark,
} from 'iconoir-react';

const iconMap = Object.freeze({
  add: Plus,
  addWorker: UserPlus,
  archive: Archive,
  assignments: TaskList,
  back: ArrowLeft,
  brandMark: Hexagon,
  budget: Coins,
  calendar: Calendar,
  close: Xmark,
  collapse: NavArrowUp,
  companies: Building,
  dashboard: Dashboard,
  deadline: Calendar,
  delete: Trash,
  disclosure: NavArrowRight,
  documents: MultiplePages,
  download: Download,
  edit: EditPencil,
  error: WarningCircle,
  expand: NavArrowDown,
  filter: FilterAlt,
  forward: ArrowRight,
  information: InfoCircle,
  hide: EyeClosed,
  logout: LogOut,
  menu: Menu,
  moreActions: MoreHoriz,
  notifications: BellNotification,
  next: NavArrowRight,
  previous: NavArrowLeft,
  projectStudio: DesignNib,
  projects: Folder,
  restore: Refresh,
  search: Search,
  settings: Settings,
  sort: Sort,
  sortDown: SortDown,
  success: CheckCircle,
  upload: Upload,
  view: Eye,
  warning: WarningTriangle,
  workers: Group,
  workOrders: ClipboardCheck,
});

export default iconMap;
