import {
    Home,
    User,
    Archive,
    Folder,
    Plus,
    Trash,
    EditPencil,
    Search,
    Settings,
    Calendar,
    Group,
    ClipboardCheck,
    Clock,
    WarningCircle,
    Eye,
    EyeClosed,
    Upload,
    Download,
} from "iconoir-react";

export const Icons = {
    home: Home,
    worker: User,
    archive: Archive,
    project: Folder,
    add: Plus,
    delete: Trash,
    edit: EditPencil,
    search: Search,
    settings: Settings,
    calendar: Calendar,
    team: Group,
    workOrder: ClipboardCheck,
    pending: Clock,
    warning: WarningCircle,
    view: Eye,
    hide: EyeClosed,
    upload: Upload,
    download: Download,
};