services:
    mysql:
        image: mysql:8.0
        container_name: atelicove-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-atelicoveDB}
            MYSQL_USER: ${DB_USERNAME:-atelicove_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-atelicove_pass}
        ports:
            - "${MYSQL_PORT:-3307}:3306" # host:container
        volumes:
            - atelicove_db:/var/lib/mysql
volumes:
    atelicove_db:
